#!/bin/bash
if [[ $# < 1 ]]
then
  BUILD=./build
else
  BUILD=$1
fi
echo "testing for link to ECO32 build directory..."
if [ ! -L $BUILD ]
then
  echo -n "please enter path to ECO32 build directory: "
  read answer
  ln -s $answer $BUILD
fi
echo -n $BUILD" --> "
readlink $BUILD
